SCREEN_WIDTH = 1600
SCREEN_HEIGHT = 900
GAPPED_SCREEN_WIDTH = SCREEN_WIDTH * 0.8
GAPPED_SCREEN_HEIGHT = SCREEN_HEIGHT * 0.8

CARD_WIDTH = GAPPED_SCREEN_WIDTH // 10
CARD_HEIGHT = GAPPED_SCREEN_WIDTH // 10
CARD_DISTANCE = GAPPED_SCREEN_HEIGHT // 180
MENU_CARD_DISTANCE = GAPPED_SCREEN_HEIGHT // 100

BOARD_CELL_WIDTH = CARD_WIDTH
BOARD_CELL_HEIGHT = CARD_HEIGHT

BUTTON_WIDTH = SCREEN_WIDTH // 12
BUTTON_HEIGHT = SCREEN_HEIGHT // 14
BUTTON_DISTANCE = SCREEN_WIDTH // 360

PORTRAIT_WIDTH = SCREEN_WIDTH // 10
PORTRAIT_HEIGHT = SCREEN_WIDTH // 10
PORTRAIT_DISTANCE = SCREEN_WIDTH // 30
HP_OFFSET = SCREEN_WIDTH // 360
HP_RECT_WIDTH = SCREEN_WIDTH // 20
HP_RECT_HEIGHT = SCREEN_WIDTH // 30

END_TURN_WIDTH = SCREEN_WIDTH // 15
END_TURN_HEIGHT = SCREEN_HEIGHT // 20
END_TURN_DISTANCE_X = SCREEN_WIDTH // 70
END_TURN_DISTANCE_Y = (
        SCREEN_HEIGHT -
        (SCREEN_HEIGHT - (BUTTON_HEIGHT + BUTTON_DISTANCE) * 5) // 2
        + SCREEN_HEIGHT // 50
)
