SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 900

CARD_WIDTH = SCREEN_WIDTH // 10
CARD_HEIGHT = SCREEN_WIDTH // 10
CARD_DISTANCES = SCREEN_HEIGHT // 180

BOARD_CELL_WIDTH = SCREEN_WIDTH // 10
BOARD_CELL_HEIGHT = SCREEN_WIDTH // 10
