SCREEN_WIDTH = 1800
SCREEN_HEIGHT = 980
GAPPED_SCREEN_WIDTH = SCREEN_WIDTH * 0.8
GAPPED_SCREEN_HEIGHT = SCREEN_HEIGHT * 0.8

CARD_WIDTH = GAPPED_SCREEN_WIDTH // 10
CARD_HEIGHT = GAPPED_SCREEN_WIDTH // 10
CARD_DISTANCES = GAPPED_SCREEN_HEIGHT // 180

BOARD_CELL_WIDTH = CARD_WIDTH
BOARD_CELL_HEIGHT = CARD_HEIGHT

BUTTON_WIDTH = SCREEN_WIDTH // 12
BUTTON_HEIGHT = SCREEN_HEIGHT // 14
BUTTON_DISTANCE = SCREEN_WIDTH // 360

PORTRAIT_WIDTH = SCREEN_WIDTH // 10
PORTRAIT_HEIGHT = SCREEN_WIDTH // 10
PORTRAIT_DISTANCE = SCREEN_WIDTH // 30
HP_OFFSET = SCREEN_WIDTH // 360
HP_RECT_WIDTH = SCREEN_WIDTH // 20
HP_RECT_HEIGHT = SCREEN_WIDTH // 30